# Generated by Django 3.2.9 on 2021-11-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211108_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
