# Generated by Django 3.2.9 on 2021-11-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211110_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constructor',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
