# Generated by Django 3.2.9 on 2021-11-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_race_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='time',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
