# Generated by Django 3.2.9 on 2021-11-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_race_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
