# Generated by Django 3.2.9 on 2021-11-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211110_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='last_name',
        ),
    ]
